/* ============================================
   PEC Typing Skills - Endless Passage Library
   Each passage: 80-150 words, grouped by category
   ============================================ */

window.PEC_PASSAGES = [
  /* ---- Technology ---- */
  { c: "Technology", t: "Modern technology has quietly become the invisible layer that supports almost every part of our daily lives. We wake up to smart alarms, navigate with digital maps and stay connected through devices that fit inside our pockets. What once required a room full of machines can now be handled by a small processor that costs less than a meal. This rapid change has made information more accessible than ever before, but it has also created a responsibility to use these tools thoughtfully and with clear purpose. The people who thrive are not those who own the newest device, but those who understand how to use any device with patience, curiosity and discipline." },
  { c: "Technology", t: "Every few years a new wave of technology arrives and reshapes the way people work. Cloud computing changed how teams store data, mobile devices changed how we communicate and intelligent systems now help us make faster decisions. The important lesson is not the device itself but the habit of learning continuously. Technology rewards those who stay curious, experiment often and remain willing to unlearn old methods when better ones appear on the horizon. Companies that ignore this habit slowly fall behind, while smaller teams that adapt quickly can reach audiences that were once impossible to find. The same principle applies to students, because the skills you practise today will look completely different in a few years." },

  /* ---- Programming ---- */
  { c: "Programming", t: "Programming is the practice of turning a clear thought into instructions that a machine can follow. A beginner starts with small steps such as printing a message or repeating a task, and slowly builds the confidence to solve larger problems. Good code is not only correct, it is also readable, organized and easy to change. When you name your variables carefully and break a problem into small functions, you are writing code that other people can understand and improve. Readability matters because most software is written once but maintained for many years by a changing team of developers." },
  { c: "Programming", t: "The best programmers spend more time thinking than typing. They read the problem twice, sketch a simple approach and only then open the editor. Debugging is a skill that grows with patience, because every error message is really a clue about what the machine expected. Over time you learn to ask better questions, test smaller pieces of logic and keep your solutions simple enough to repair without fear. Rushing to a solution usually creates more work later, while a few minutes of quiet planning often removes the bug before it is ever written." },

  /* ---- Artificial Intelligence ---- */
  { c: "Artificial Intelligence", t: "Artificial intelligence systems learn patterns from large amounts of data instead of following rules written by hand. This allows them to recognise speech, translate languages and suggest what we might enjoy next. The technology is powerful, but it is not magic. Behind every intelligent result there is careful preparation, clean data and engineers who test the system again and again. Understanding both the strength and the limits of these models helps us use them responsibly. A model can suggest an answer, yet a human being must still decide whether that answer is fair, safe and appropriate for the situation." },
  { c: "Artificial Intelligence", t: "Machine learning models improve through feedback, much like a student who learns from corrections. When a prediction is wrong, the system adjusts and tries again millions of times until its answers become reliable. This process has made remarkable progress in medicine, finance and education. Still, humans remain at the centre of every decision that matters. The goal of artificial intelligence is not to replace people, but to give them better tools for thoughtful and faster work. Students who learn how these systems work will be ready to guide them rather than simply follow wherever they lead." },

  /* ---- Cybersecurity ---- */
  { c: "Cybersecurity", t: "Cybersecurity begins with simple habits that most people overlook. A strong password, a different password for every account and an extra verification step can stop a large number of attacks. Hackers often do not break through complex systems; they trick ordinary users into opening a door for them. Staying alert to unusual messages, checking links before clicking and updating software regularly are small actions that protect your identity, your money and the data of everyone who trusts you. Security is rarely dramatic, and that is exactly why it works: quiet habits repeated every single day." },
  { c: "Cybersecurity", t: "A secure system is designed with suspicion in mind. It assumes that passwords may leak, networks may be watched and users may make mistakes. For this reason, engineers encrypt sensitive data, limit access to only those who need it and keep detailed logs of every important action. Security is never a product you buy once. It is a continuous process of learning about new threats, testing your defences and responding quickly when something unexpected happens. Organisations that treat security as a one-time project discover the cost of that decision when an incident finally arrives." },

  /* ---- Web Development ---- */
  { c: "Web Development", t: "Web development blends structure, style and behaviour into a single experience. HTML gives a page its meaning, CSS shapes its appearance and JavaScript adds interaction that responds to the user. A well built website loads quickly, works on every screen size and remains easy to navigate with a keyboard. Great front end work is invisible, because visitors notice the content rather than the code that delivers it. That quiet reliability is the real reward of careful development. When a page simply works on every device, people trust it without ever knowing how much effort was required." },
  { c: "Web Development", t: "Modern web teams move quickly by breaking large projects into small components. A button, a card or a navigation bar becomes a reusable piece that many pages can share. This approach keeps the design consistent and makes fixes easier to apply. Developers also test their work in several browsers, because a detail that looks perfect on one screen may behave differently on another. Consistency across devices is what makes a website feel professional. Teams that write tests and review each other's work spend far fewer nights repairing problems that nobody expected." },

  /* ---- Computer Science ---- */
  { c: "Computer Science", t: "Computer science is the study of information, computation and the systems that process both. It begins with simple questions: how do we represent data, how do we search it efficiently and how do we prove that an algorithm will finish. From these foundations grow operating systems, databases and networks that support modern life. The subject rewards logical thinking, but it also asks for creativity, because the elegant solution is often the one nobody has written before. Each new concept you master makes the next one feel natural, which is why steady progress beats occasional bursts of effort." },
  { c: "Computer Science", t: "Understanding data structures is like choosing the right container for a task. A list keeps things in order, a set removes duplicates and a tree keeps information balanced for fast lookup. Choosing well can reduce a slow program to one that feels instant. Students who practise these choices on small problems build the intuition needed for larger systems, where a poor decision can affect thousands of users who will never see the code behind the screen. The best engineers learn to justify every choice, because unexplained decisions become expensive problems in the future." },

  /* ---- Internet ---- */
  { c: "Internet", t: "The internet is a network of networks, where messages travel in small packets across many machines before reaching their destination. This design makes it remarkably resilient, because traffic can always find another path. What users experience as a single page is actually a conversation between browsers, servers and services spread across the world. Learning how this conversation works makes the online world feel less mysterious and helps you understand why speed, privacy and reliability matter so much. Every click triggers a journey you never see, and understanding that journey makes you a smarter user of the web." },
  { c: "Internet", t: "Connection speeds have improved enormously, yet patience remains a useful online skill. Not every page needs to load instantly and not every notification deserves a reply. The internet offers endless material, so the real challenge is selection. People who build a deliberate reading habit, follow reliable sources and take regular breaks tend to learn more than those who scroll without direction. Digital maturity is largely the art of choosing what to ignore. A calm relationship with the internet leaves more time for the deep work that actually moves your goals forward." },

  /* ---- Space ---- */
  { c: "Space", t: "Space exploration reminds us how small our planet is and how large the unanswered questions remain. Robotic probes have visited every planet in our solar system, while telescopes collect light from galaxies that began shining billions of years ago. Each mission takes decades of planning, precise mathematics and international cooperation. The rewards go far beyond discovery, because the same engineering that guides a spacecraft also improves medicine, materials and communication systems here on Earth. Exploring space therefore doubles as an investment in ordinary life, even when the rocket itself never returns." },
  { c: "Space", t: "Looking at the night sky is a lesson in distance. The light reaching your eyes may have started its journey before humans invented writing. Astronomers measure this distance in light years, a unit that quietly explains why space is so difficult to explore. Yet curiosity keeps us building larger rockets and smarter instruments. Every new image of a distant world adds another sentence to a story that our species has only just begun to read, and each discovery reminds us that questions are more valuable than certainty." },

  /* ---- Science ---- */
  { c: "Science", t: "Science advances by asking careful questions and designing fair tests to answer them. A good experiment can prove an idea wrong, and that is exactly why the method works. Researchers repeat their work, share their data and invite others to challenge the result. This culture of open criticism is slower than opinion, but it is far more reliable. Over time, small confirmed findings combine into knowledge that can change medicine, energy and the way we understand nature. The strength of science lies in its willingness to abandon any belief that fails an honest test." },
  { c: "Science", t: "Curiosity is the engine of scientific progress, but discipline keeps it on track. A hypothesis must be stated clearly enough to be tested, and the results must be recorded honestly, even when they disappoint. The most valuable skill a young scientist can develop is patience with failure. Every rejected theory narrows the search and brings the next experiment closer to something true, useful and ready to be shared with the wider world. Students who record negative results carefully often discover the most interesting direction for their next line of work." },

  /* ---- Innovation ---- */
  { c: "Innovation", t: "Innovation rarely arrives as a single brilliant idea. It usually appears when someone notices an ordinary frustration and decides to solve it properly. The process is messy: early attempts fail, assumptions break and plans change. What separates innovators from dreamers is the willingness to test quickly, listen to honest feedback and improve the solution step by step. Progress is not about being perfect on the first try, it is about learning faster than the problem grows. Teams that celebrate small verified improvements consistently outperform teams that wait for one perfect breakthrough." },
  { c: "Innovation", t: "The strongest innovations solve a real problem for real people. New technology only matters when it fits into someone's day and makes that day better. Teams that spend time observing users often discover that the biggest improvement is not a new feature but the removal of a confusing step. Restraint is a creative skill. Knowing what not to build is just as important as knowing what to build next, and the discipline to say no keeps a product focused on the people it promised to serve." },

  /* ---- Startups ---- */
  { c: "Startups", t: "A startup begins with a simple belief: that a specific group of people has a problem worth solving. The early days are about testing that belief as cheaply as possible. Founders talk to customers, build small versions of their idea and measure whether anyone truly cares. Growth comes later. Survival depends on clarity, focus and the discipline to ignore distractions that do not move the core idea forward toward real value. A team that speaks with ten genuine users often learns more than a month of internal debate ever could produce." },
  { c: "Startups", t: "Building a company teaches you to make decisions with incomplete information. You will never have every answer, so you learn to estimate, act and adjust. Teams that communicate honestly recover from mistakes faster than teams that hide them. Money matters, but trust matters more, both with customers and within the group. A startup that keeps its promises, even when it is small, earns the reputation that later opens every important door. Reputation travels faster than advertising, especially in a market where everyone eventually speaks to everyone else." },

  /* ---- General Knowledge ---- */
  { c: "General Knowledge", t: "General knowledge is the quiet advantage that helps you take part in any conversation. It grows naturally when you read widely, travel when you can and stay curious about subjects outside your own field. History explains how decisions made long ago still shape today's borders, laws and languages. A little understanding of geography, economics or medicine makes news easier to follow and opinions easier to question. Learning never truly stops at the edge of a syllabus, and the habit of asking why will serve you long after any examination is finished." },
  { c: "General Knowledge", t: "The world is connected in ways that are easy to overlook. A change in one country's trade policy can raise prices in another, while a discovery in a small laboratory may transform an entire industry. Reading newspapers, watching documentaries and discussing ideas with people who think differently all strengthen your understanding. The goal is not to know everything, but to build a framework that helps you place each new fact in its proper context. With that framework in place, even unfamiliar information quickly becomes something you can reason about." },

  /* ---- Student Life ---- */
  { c: "Student Life", t: "Student life is about balance more than perfection. Classes, projects, friendships and rest all compete for the same limited hours, and the students who manage well are usually the ones who plan honestly. A realistic timetable with small daily goals beats an ambitious schedule that collapses by Wednesday. Asking for help early, reviewing notes regularly and protecting a full night of sleep will carry you further than last minute effort ever could. The goal is not to look busy, but to keep steady progress without burning out halfway through the term." },
  { c: "Student Life", t: "The habits you build as a student tend to follow you into your career. Learning to start early, write clearly and meet a deadline without panic is worth more than a single impressive mark. Students who join discussions, attend workshops and help classmates often discover that teaching is the fastest way to understand a subject. Growth happens outside the classroom just as often as inside it, whenever you choose to take part. Every extra effort you make now becomes a story you can tell honestly in a future interview." },

  /* ---- College ---- */
  { c: "College", t: "College is more than a sequence of courses. It is a place where you meet people who think differently, try ideas that might fail and discover which kind of work keeps your attention for hours. Professors respond well to students who come prepared and ask specific questions, and seniors often share advice that no textbook contains. The effort you invest in building genuine relationships and practical skills will return value long after the final exam has ended. The friendships formed during difficult projects often become the strongest professional networks a graduate will ever have." },
  { c: "College", t: "A campus offers resources that rarely exist anywhere else: libraries, laboratories, clubs, competitions and mentors with real experience. Students who use these resources deliberately graduate with more than a certificate. They leave with a portfolio, a network and a clearer sense of direction. It is worth attending a few events outside your branch of study, because unexpected interests sometimes grow into careers that feel less like work and more like purpose. Every unused resource is a quiet opportunity missed, so ask what your college provides before assuming it is unavailable." },

  /* ---- Productivity ---- */
  { c: "Productivity", t: "Productivity is not about doing more things, it is about doing the right things with full attention. Deep work happens when distractions are removed and one task is allowed to occupy your mind completely. Short breaks between focused periods keep the brain fresh, while a written list prevents important work from being forgotten. At the end of the day, progress is measured by what moved forward, not by how busy the calendar appeared to be. A single completed task of real value is worth more than a dozen half finished ones." },
  { c: "Productivity", t: "Small systems beat strong willpower. When a good habit has a fixed time, a clear trigger and an easy first step, it requires almost no motivation to begin. Track your work honestly, review what slowed you down and adjust one thing at a time. Consistency compounds quietly, and after a few weeks the routine that once felt difficult becomes the natural way you start every productive morning. The students who appear effortlessly organised have usually spent months building invisible systems that make the right choice the easiest choice." },

  /* ---- Motivation ---- */
  { c: "Motivation", t: "Motivation is unreliable, so the strongest students build routines that work even when enthusiasm fades. They set a clear reason for their effort, keep the next step small and celebrate progress rather than waiting for a final victory. Difficult days are part of the process, not a sign that you should quit. What matters is returning to the task tomorrow, a little better prepared and a little more experienced than you were before. Growth is rarely visible on a single day, but the record of many days tells a clear story." },
  { c: "Motivation", t: "Comparison can either lift you or drain you, depending on how you use it. Watching someone ahead of you is useful when it reveals a method you can adopt, and harmful when it makes your own progress feel small. Measure yourself against yesterday's version of your work. Every hour you practise, every mistake you correct and every concept you finally understand moves the line forward, even when the change is invisible on a busy day. Quiet, unremarkable effort is still the most reliable path to remarkable results." },

  /* ---- Future Technology ---- */
  { c: "Future Technology", t: "The technologies of the next decade are already taking shape in laboratories and small research teams. Quantum computers promise to solve certain problems that would take today's machines an unreasonable amount of time. Advanced materials will make batteries lighter and solar cells cheaper, while biotechnology will help doctors treat disease with greater precision. None of these advances arrives overnight, and each one depends on patient investment, careful testing and people willing to work on problems without quick rewards. The breakthroughs of tomorrow are being prepared by ordinary sessions of focused work happening today." },
  { c: "Future Technology", t: "Predicting the future of technology is difficult because breakthroughs rarely follow a straight line. A tool built for one purpose often transforms a completely different field years later. What we can predict is the direction of travel: systems will become more connected, more automated and more demanding of people who understand how they work. Learning the fundamentals now prepares you to adapt quickly when the specific tools of tomorrow inevitably change. Flexibility, built on a strong base, is the most durable career strategy available to a student." },

  /* ---- Digital World ---- */
  { c: "Digital World", t: "Life in the digital world leaves a trail of choices behind every click. What we post, share and search for becomes part of a permanent record that can be seen by far more people than we imagine. Digital literacy means understanding this reality and acting accordingly. It includes protecting your privacy, checking the source of a claim and thinking before responding in anger. A thoughtful online presence opens doors that a careless one quietly closes, and the habit of pausing before posting is one of the most valuable skills of this decade." },
  { c: "Digital World", t: "Screens connect us to the entire world, yet they can still leave us feeling alone if the interactions remain shallow. The digital world rewards those who create instead of only consuming. Writing an article, building a tool or sharing a useful tutorial takes more effort than scrolling, but it builds skills and reputation that last. Every small contribution you publish becomes a stepping stone toward larger opportunities you cannot yet foresee. Over a year, a modest library of your own work can completely change how strangers and employers perceive you." },

  /* ---- Coding ---- */
  { c: "Coding", t: "Learning to code is really learning to think in steps. Before a computer can help you, you must describe the solution clearly enough for it to follow without guessing. Beginners often fear errors, but experienced developers read messages calmly and treat each one as feedback. The first solution does not need to be elegant; it only needs to work. From there, careful editing gradually turns a rough script into something clean, fast and easy to maintain. Every program you finish teaches you more than three programs you abandon halfway through." },
  { c: "Coding", t: "Practice matters more than talent in coding, and the quality of that practice matters most of all. Typing examples without understanding produces fragile knowledge, while solving small unfamiliar problems builds real skill. Reading other people's code is equally valuable, because it exposes you to techniques you would never have invented alone. Over months of steady effort, patterns begin to appear, and problems that once looked impossible now seem like variations of something you have already solved. Confidence in programming is simply memory plus practice, carefully combined over time." },

  /* ---- Open Source ---- */
  { c: "Open Source", t: "Open source software is built in the open, with source code that anyone may read, use and improve. This model powers much of the modern internet, from web servers to mobile systems. Contribution does not always mean writing complex code; documenting a feature, reporting a clear bug or improving a translation all move a project forward. Working with others you have never met teaches you communication, review and the patience to accept feedback from a global community. Those soft skills often prove just as valuable as the technical knowledge you gain along the way." },
  { c: "Open Source", t: "Choosing an open source project to join can feel intimidating at first. The best starting point is usually a project you already use, because you understand its purpose and feel its problems directly. Read the contribution guide, look for small issues marked for newcomers and ask questions politely before writing code. Reputation in open source is earned slowly through consistent, honest contributions, and once earned it follows you across the industry. A single thoughtful pull request can open a conversation that eventually leads to a job, a mentor or a lasting friendship." },

  /* ---- Software Engineering ---- */
  { c: "Software Engineering", t: "Software engineering treats building programs as a team discipline rather than a solo act. It values clear requirements, tested code, version control and reviews that catch problems before users ever see them. A feature is not finished when it runs once on a developer's machine; it is finished when it behaves predictably under load, failure and change. This wider definition of quality is what separates professional systems from experiments that only work in perfect conditions. Engineering is the difference between a demo and a product that people can depend on every day." },
  { c: "Software Engineering", t: "Maintenance is where most of a software project's lifetime is spent. Requirements shift, dependencies update and new team members arrive without context, so good engineers write code that explains itself. Tests act as a safety net that allows confident changes, while documentation records the reasons behind decisions. A project that is easy to modify will outlive a cleverer one that only its original author can safely touch. Writing for the next reader is a form of respect, and it repays itself many times over." },

  /* ---- PEC / Community ---- */
  { c: "PEC Community", t: "The Programming Excellence Community brings students together around a shared goal: to become better problem solvers through consistent practice. Members learn from mentors, discuss approaches after class and support each other through difficult challenges. A community like this matters because progress accelerates when you are not working alone. Explaining an idea to someone else deepens your own understanding, while watching a peer solve a problem introduces you to a method you had not considered. Every session attended is a small deposit into a skill that compounds for years." },
  { c: "PEC Community", t: "Skill grows fastest in an environment where showing your work is encouraged and mistakes are treated as part of learning. The Programming Excellence Community creates that environment through regular sessions, shared projects and honest feedback. Every participant contributes something, whether it is a finished solution, a careful review or simply the effort to keep showing up. Over a semester, these small contributions become a culture of excellence that outlasts any single event. New members quickly discover that the community is measured by how generously it shares what it knows." },
  { c: "PEC Community", t: "Regular practice sessions give students a rhythm that is difficult to build alone. When a community meets consistently, members begin to notice patterns in each other's progress, celebrate improvements and identify where a little extra help is needed. Collaboration also prepares students for real workplaces, where code is reviewed, ideas are debated and the strongest solution usually wins regardless of who proposed it. Learning this early makes the transition to professional development far smoother and far less intimidating for everyone involved." },
  { c: "PEC Community", t: "Strong technical communities are built on more than code reviews and contests. They thrive when members feel comfortable asking basic questions, sharing unfinished work and admitting what they do not yet understand. The Programming Excellence Community values this openness, because confidence grows quickly in a supportive group. Over time, students who once hesitated to speak up begin leading sessions themselves, passing the same encouragement forward to the next group of learners. That cycle of teaching and learning is what keeps a community alive long after a single batch of students graduates." }
];
